---
- import_playbook: ../docker/docker.ansible.yml
    
- name: Install Romm Manager
  hosts: all
  become: true
  vars:
    base_dir: /opt/romm
    roms_dir: /mnt/roms

  tasks:
    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ base_dir }}/config"
        - "{{ roms_dir }}/library"
        - "{{ roms_dir }}/assets"
        
    - name: Copy compose.yml
      copy:
        dest: "{{ base_dir }}/compose.yml"
        src: ./compose.yml
    
    - name: Copy secrets.env
      copy:
        dest: "{{ base_dir }}/secrets.env"
        src: ./secrets.env
        mode: '0600'

    - name: Start Docker Compose Services
      command: docker compose -f "{{ base_dir }}/compose.yml" up -d
      args:
        chdir: "{{ base_dir }}"