---
- import_playbook: ../docker/docker.ansible.yml

- import_playbook: ../docker-compose/docker-compose.ansible.yml
  vars:
    app_name: overleaf
    data_dirs:
      - data
    use_secrets: true
    custom_files:
      - src: "mongodb-init-replica-set.js"
        dest: "mongodb-init-replica-set.js"
        mode: "755"