version: "3.8"

services:
  app:
    image: ghcr.io/danielbrendel/hortusfox-web:latest
    ports:
      - "8080:80"
    volumes:
      - app_images:/var/www/html/public/img
      - app_logs:/var/www/html/app/logs
      - app_backup:/var/www/html/public/backup
      - app_themes:/var/www/html/public/themes
      - app_migrate:/var/www/html/app/migrations
    env_file:
      - ./secrets.env
    environment:
      APP_ADMIN_EMAIL: "admin@puccia.org"
      APP_TIMEZONE: "UTC"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hortusfox
      DB_USERNAME: user
      DB_CHARSET: "utf8mb4"
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    env_file:
      - ./secrets.env
    environment:
      MARIADB_DATABASE: hortusfox
      MARIADB_USER: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  app_images:
  app_logs:
  app_backup:
  app_themes:
  app_migrate: