---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Europe/Rome
    volumes:
      - /opt/books/config/calibre:/config
      - /opt/books/library:/books
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped