---
- name: Install Docker using official script
  hosts: all
  become: true

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'
    
    - name: Run Docker installation script
      command: sh /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker
      register: docker_install
    
    - name: Display installation output
      debug:
        var: docker_install.stdout_lines
      when: docker_install.changed
    
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
    
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false
    
    - name: Display installed Docker version
      debug:
        var: docker_version.stdout
    
    - name: Remove installation script
      file:
        path: /tmp/get-docker.sh
        state: absent