---
- name: Deploy Nextcloud AIO to LXC Container
  hosts: all
  become: true
  vars:
    compose_file_path: /root/compose.yml
  
  tasks:
    - name: Ensure target directory exists
      file:
        path: "{{ compose_file_path | dirname }}"
        state: directory
        mode: '0755'
    
    - name: Copy Docker Compose file
      copy:
        src: compose.yml
        dest: "{{ compose_file_path }}"
        owner: root
        group: root
        mode: '0644'
