services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      - TZ=Europe/Rome
    volumes:
      - /opt/grocy/config/core:/config
    ports:
      - 9283:80
    restart: unless-stopped